version: "3.6"
services:
  djdev:
    build: .
    restart: on-failure
    working_dir: /code
    # set user to root, group to www-data. All files should be delete-able by www-data group.
    # problem is that they are read only for group www-data. Use make perm to make them writable.
    user: "0:33"
    env_file:
      - ./.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      # use pip cache to reduce startup time..
      # https://stackoverflow.com/questions/25305788/how-to-avoid-reinstalling-packages-when-building-docker-image-for-python-project
      - ../datasys/python-dot-cache/pip/:/root/.cache/pip
    ports:
      - "6461:8000"
    networks:
      - 499d-django_default      
  
  adminerd:
    # 10.4.1.231:6117/
    # image: adminer:4.7
    # image: dockette/adminer:full
    build: ./adminer-sqlite
    restart: always
    ports:
      - 14123:80
      # 8080 for regular adminer, 80 for dockette
    volumes:
      - ./db.sqlite3:/db.sq3
      - ./adminer-sqlite:/var/www/html
    environment:
      - ADMINER_DEFAULT_SERVER=s
      - DB_PATH=/db.sq3
      - DB_USER=u 
      - DB_PASS=a
      # - ADMINER_PLUGINS='tables-filter'


networks:
  499d-django_default:
    name: 499d-django_default

    #  
      #
        #   depends_on:
        #     - db
        # db:
        #   image: "postgres:10.3-alpine"
        #   restart: unless-stopped
        #   env_file:
        #     - ./.env
        #   ports:
        #     - "5432:5432"
        #   volumes:
        #     - ./postgres/data:/var/lib/postgresql/data
        


